### ISSUE TITLE
Plugin issue on local and server

### ISSUE THREAD

**Issue by aytac** [bromagosa/Snap4Arduino-plugin#8]
Hi there,

I'm having a plugin issue on my local as well as in my server.
When I check the plugin and codes, I couldn't find out what the exact problem is, to be honest.

I have follow the all steps while I'm install plugin and snap4arduino itself but I have attached issues below. I cannot connect my arduino. I'm pretty sure that it's about the Snap4Arduino connector plugin.

Is there any way to fix it?

Thanks

Aytac
![1](https://cloud.githubusercontent.com/assets/6682773/18548034/7cf4df30-7b3e-11e6-9ad9-e82d58096874.JPG)
![2](https://cloud.githubusercontent.com/assets/6682773/18548035/7cf57f44-7b3e-11e6-9362-538f44087c87.JPG)
![3](https://cloud.githubusercontent.com/assets/6682773/18548036/7cf6716a-7b3e-11e6-8cd6-cca37d6c641b.JPG)

**Comment by bromagosa** [comment]
Hi!

Let me take a look, I think I may have removed the permission for the plugin to connect to local machines by mistake :worried:

By the way, I'm finishing up a much simpler packager for all versions, including desktop, web and ChromeOS, so I'll very soon deprecate this repository as the new one is superseding it :)

**Comment by bromagosa** [comment]
@aytac can you please try with the version I'm attaching?

[Snap4Arduino-web.zip](https://github.com/bromagosa/Snap4Arduino-plugin/files/476322/Snap4Arduino-web.zip)

**Comment by aytac** [comment]
Hi bromagosa,

Thanks you for your time.
I have tried that in my local with a simple python server. It gives me the same error in console log.

Please see the attached.

The weird thing is when I try http://46.140.176.36/ this site with the same extension I have been using, it works.
![1](https://cloud.githubusercontent.com/assets/6682773/18580481/c63f55ca-7bf3-11e6-8e1b-7a0ca1a3da94.JPG)

When I run on chrome first it asks me allow to communicate with the s4a connector and then all ports appear under the connect arduino.

Mine is same with the error as it was.

_Error in event handler for (unknown): TypeError: Cannot read property 'forEach' of undefined_

Are those codes you have sent to me same codes you use on the server 46.140.176.36?

Thanks

Aytac

**Comment by bromagosa** [comment]
Oh I see! Please try to run your local server through port 8080 and see what happens...

**Comment by aytac** [comment]
That's so weird.
I do something wrong. It doesn't even ask me to allow communicate with s4a extension.

![2](https://cloud.githubusercontent.com/assets/6682773/18581207/72f4831e-7bf7-11e6-9941-ea3c83ff8905.JPG)
![3](https://cloud.githubusercontent.com/assets/6682773/18581206/72f326e0-7bf7-11e6-9947-4a42f3b6c539.JPG)
![4](https://cloud.githubusercontent.com/assets/6682773/18581208/72f512e8-7bf7-11e6-8023-66ee8efe732c.JPG)

**Comment by bromagosa** [comment]
Wait, did you close the other connection? This error also occurs when there are no serial ports available.

**Comment by aytac** [comment]
Sorry Bernat, what other connection?

**Comment by bromagosa** [comment]
The one at 46.140.176.36. The plugin can only communicate with one web client at a time, so if you have that tab open you'll need to close it first.

Here's mine working right now:

![image](https://cloud.githubusercontent.com/assets/1016697/18581607/a7d8ba96-7c01-11e6-8946-3de558921f8d.png)

**Comment by aytac** [comment]
Oh my!
That's working :100: 
You rock Bernat definitely..
Thank you so much. We'd like to translate whole S4A project into Turkish, as well.

**Comment by bromagosa** [comment]
Great! Glad to hear! :happy:

As you see, there are a couple of rough corners to polish still... these errors should be deal with and pop up in the UI, not in the console.

Next week I'm going to deploy the first batch of automatically built packages with the new packaging script I'm finishing up, then it's going to be much easier for me to tackle particular issues for each version.

As for translations, more than welcome! You can use [this template](https://github.com/edutec/Snap4Arduino/blob/multiplatform/src/s4a/lang-template.js) for your translation.

Thank you!
